### ISSUE TITLE
Missing Dependencies(Maven)

### ISSUE THREAD

**Issue by JeremyCarlsten** [Sayi/swagger-diff#12]
Looks like maven is missing the version of jcommander you are using. 

[Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A"com.beust"%20AND%20a%3A"jcommander")

Worked around this by excluding the jcommander dependency and depending on the latest version 1.72

**Comment by Sayi** [comment]
The actual version of jcommander dependency is also 1.72.
