### ISSUE TITLE
SLF4J runtime error for swagger-diff v1.2.1

### ISSUE THREAD

**Issue by phillipkent** [Sayi/swagger-diff#19]
Hi. With new v1.2.1 I am getting this error/warning in runtime:

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

This is my Java environment:
> java 10.0.2 2018-07-17
> Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
> Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**Comment by Sayi** [comment]
Are you using the command line tool? I re-uploaded the package and fix the problem： https://github.com/Sayi/swagger-diff/releases/tag/v1.2.1

**Comment by phillipkent** [comment]
Great. Problem is fixed with the new upload.
